# Generated by Django 4.2.5 on 2024-02-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manifacturer', 'verbose_name_plural': 'Manifacturers'},
        ),
    ]
